using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LemonadeStand
{
    abstract class Days
    {
        public string customerPool;
        public string todaysTemp;   // generated by seasonal ranges
        public string todaysHumidity; 
    }
}
